//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KuaförRandevuSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblLisans
    {
        public int Id { get; set; }
        public string LisansCode { get; set; }
        public string HDD { get; set; }
        public string PC { get; set; }
        public string MacAdres { get; set; }
        public string IpAdres { get; set; }
    }
}
