//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KuaförRandevuSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblRandevu
    {
        public int Id { get; set; }
        public Nullable<int> MusteriId { get; set; }
        public Nullable<System.DateTime> RandevuTarih { get; set; }
        public string RandevuSaat { get; set; }
        public Nullable<int> TrasTip { get; set; }
        public Nullable<bool> RandevuDurum { get; set; }
    
        public virtual TblMusteri TblMusteri { get; set; }
        public virtual TblTras TblTras { get; set; }
    }
}
